name: wiki_link_core
description: Classes shared between wikipedia_scraper and wiki_link_monitor.
version: 0.1.0+3
repository: https://github.com/Wii42/wiki_link_core

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  html: ^0.15.4
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
